#!/usr/bin/env bash
# redirecting permanently to Youtube

redirect="\tlocation /redirect_me {\
\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4\
\n\t}"

sed -e 47i\\"$redirect" -i /etc/nginx/sites-available/default
