#!/usr/bin/env bash
# Installation of Nginx and redirecting permanently to Youtube

apt install update -y
apt install nginx -y 
ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.html
service nginx restart
redirect="\tlocation /redirect_me {\
\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4\
\n\t}"

sed -e 47i\\"$redirect" -i /etc/nginx/sites-available/default
