#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string

apt install update -y
apt install nginx -y 
ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.html

custom_404="Ceci n'est pas une page"

echo -e "$custom_404" > /var/www/html/404.html

sed -e 's/^.*error_page 404.*$/\terror_page 404 \/404.html;/' -i /etc/nginx/sites-available/default

service nginx restart
